name: Update COVID-19 data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch OR schedule cron
on:
  schedule:
  - cron: '35 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup addition packages
        run: yes | sudo apt-get install sendmail

 #     - name: Setup PHP
 #       run: php -i
 #       uses: shivammathur/setup-php@v2
 #       with:
 #         php-version: '7.4'
 #         extensions: mbstring, intl
 #         ini-values: memory_limit=256M, short_open_tag=On

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update script
        run: php -d short_open_tag=On -f covid-19/scripts/import/import.php ../

      - name: Check emails log
        run: |
          php -r "sleep(50);"
          sudo tail /var/log/mail.log

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
#          git add -A
#          git commit -m "Counting summary once a day"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
